import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import Providerr from "@/toolkit/Providerr";

const janna_lt = localFont({
  src: [
    { path: "../fonts/ArbFONTS-ArbFONTS-Janna-LT-Bold.woff", weight: "700" },
    { path: "../fonts/ArbFONTS-JannaLT-Regular.woff", weight: "400" },
  ],
});

export const metadata: Metadata = {
  title: "Muslima Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale} dir={locale == "ar" ? "rtl" : "ltr"} data-scroll-behavior="smooth">
      <NextIntlClientProvider messages={messages}>
        <body className={`${janna_lt.className} antialiased`}>
          <Providerr>{children}</Providerr>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
